### ISSUE TITLE
New BASED-CS-DL Branch

### ISSUE THREAD

**Issue by NovaAndrom3da** [ThatOneCalculator/BASED-LICENSE#5]
I have created a branch of the license to allow for usage in closed-source programs and program bundles. It also allows for dependencies and other software that requires the one licensed under [BASED-CS-DL](https://github.com/Froggo8311/BASED-LICENSE/tree/BASED-CS-DL) to be under a different license. You can add it to a branch of this head repo if you wish.

**Comment by ThatOneCalculator** [comment]
the BASED license is ***only*** for open source software.

**Comment by NovaAndrom3da** [comment]
@ThatOneCalculator What I was saying was that it could be used as a dependency to closed source software, but the original software that contained the license would be open source.

**Comment by ThatOneCalculator** [comment]
Every component of software relating to the BASED license outside of external networking services should be open source
