### ISSUE TITLE
I have epicly trolled by myself by being bad at writing licenses (aka this isn't a legally viable license) :trollface:

### ISSUE THREAD

**Issue by TechnologyClassroom** [ThatOneCalculator/BASED-LICENSE#6]
I get that this is a meme license, but I want to point out that the software license cannot legally control the output of a program.  See the question ["Is there some way that I can GPL the output people get from use of my program? For example, if my program is used to develop hardware designs, can I require that these designs must be free? (#GPLOutput)"](https://www.gnu.org/licenses/gpl-faq.html#GPLOutput) from the GPL FAQ.

The [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/) license should cover everything else that is mentioned in this license.

**Comment by TechnologyClassroom** [comment]
I do agree that NFTs are bad in general.

**Comment by ThatOneCalculator** [comment]
If anything this license is meant to act as a "legal scare", people dumb enough to do NFTs won't know the intricacies of copyright law.

**Comment by TechnologyClassroom** [comment]
Having a goal of spreading FUD about copyright law through a software license is probably not a good strategy.

**Comment by ThatOneCalculator** [comment]
What would you suggest instead, then?

**Comment by ddevault** [comment]
I also noticed this problem and filed to have a package removed from Alpine Linux on the basis that this is a non-free license. I hate NFTs with a passion, but software licenses is not the appropriate place to fight this battle.

**Comment by ddevault** [comment]
Oh: the closed source clause is problematic, too. There's no definition of "closed source" given, and licenses which aim to be viral have to take a different approach (see the GPL or MPL). License writing is not the domain of amateurs.

**Comment by ThatOneCalculator** [comment]
> I also noticed this problem and filed to have a package removed from Alpine Linux on the basis that this is a non-free license. I hate NFTs with a passion, but software licenses is not the appropriate place to fight this battle.

Which package?

**Comment by ddevault** [comment]
https://github.com/MrGlockenspiel/activate-linux

https://gitlab.alpinelinux.org/alpine/aports/-/issues/13818

**Comment by ThatOneCalculator** [comment]
Honestly I might retire this license and clarify it's a joke, I only really wrote it for one repo people used to make NFTs against my will

**Comment by TechnologyClassroom** [comment]
> What would you suggest instead, then?

I would point people to use [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/) instead as it is free culture and copyleft license that covers all of the topics addressed by this license that can be enforced.  [GPL-3.0-or-later](https://www.gnu.org/licenses/gpl.txt) or [AGPL-3.0-or-later](https://www.gnu.org/licenses/agpl.txt) could also be recommended as they are the closest copyleft software licenses that only exclude the attribution portion and are battle tested through the courts.  I would move anti-NFT writings to a blog or something that is not in a license.

Retiring the license would probably be a good idea as it is nonfree in its current form and would take a considerable amount of work to become a legally enforceable license.  [Relevant xkcd](https://m.xkcd.com/927/).

**Comment by ThatOneCalculator** [comment]
Got it. Also, thoughts on the MPL 2?

**Comment by ddevault** [comment]
MPL 2.0 is a great license, I use it for several projects.

**Comment by TechnologyClassroom** [comment]
MPL-2.0 is a free license [compatible with GPL](https://www.gnu.org/licenses/license-list.en.html#MPL-2.0).  It is fine, but I prefer AGPL-3.0-or-later for code and CC-BY-SA-4.0 for everything else.

**Comment by ThatOneCalculator** [comment]
See 2c75a1308e80838a7219fea4683ef0ac5e0b509c

**Comment by ddevault** [comment]
Thanks!

**Comment by MrGlockenspiel** [comment]
Did I actually singlehandedly cause this lmao

**Comment by ThatOneCalculator** [comment]
Yea :((

I just wanted funny license for me and friends and it turned into a legal/moral thingy I'm too dumb and gay for all this

**Comment by ThatOneCalculator** [comment]
https://user-images.githubusercontent.com/44733677/168942444-f5d48da9-41f0-42b1-8229-3b369f4c2b53.mp4

**Comment by MrGlockenspiel** [comment]
the license was simply too based for us mortals

**Comment by ThatOneCalculator** [comment]
I would also like to add [this](https://stop.voring.me/notes/8zk7z02lgy)

**Comment by Jocadbz** [comment]
Oh no. i need to change LICENSE on my repos now :(
>feelsbadman

**Comment by ThatOneCalculator** [comment]
> Oh no. i need to change LICENSE on my repos now :(
> >feelsbadman

If it's a smaller repo (like under 100 stars ish) I really wouldn't worry too much. Technically viable, even if it's not entirely legally defendable.
