### ISSUE TITLE
Minor revisions

### ISSUE THREAD

**Issue by blzby1** [ThatOneCalculator/BASED-LICENSE#7]
I came across your licence and thought some improvements could be made.

The term "Original Author" needs to be specified in the beginning and needs to be used in place of the generic "the author", because it makes a paradox of the original author and author that may have modified the source code, because "the author" could pose as the original author in some rules/sentences.

Lines 42-43 contain non-legal language like "that's on you", so you might want to clean that up.

The phrases non-free, closed-source and open source need to be clarified, they are terms that are used multiple times without being defined in the beginning. This could create some legal loopholes. 

Also, the last paragraph's wording is very confusing. I'll leave that up to you to decide how to fix it.

**Comment by ThatOneCalculator** [comment]
I literally do not care :trollface:

**Comment by blzby1** [comment]
wow!

**Comment by blzby1** [comment]
Just trying to help bro ¯\_(ツ)_/¯

**Comment by ThatOneCalculator** [comment]
1. Not a bro
2. IDC
